### ISSUE TITLE
рекомендованные требования к ресурсам для быстрого старта

### ISSUE THREAD

**Issue by oserikov** [bykvaadm/SuzenEscape#57]
Добрый день! Подскажите, пожалуйста, есть ли примерные требования к ресурсам для того, чтобы поднять suzenescape? Зависит ли это от потенциального кол-ва пользователей и если да, то как?

**Comment by bykvaadm** [comment]
Добрый. 2 ядра 4 гига памяти мне хватало для студенческой группы в 20-30 человек. от количества пользователей зависит, но основная нагрузка идет только когда запускаются тяжёлые таски, например с лабиринтом. для конференции я тогда запускал на 2-х серверах 4cpu\8ram, этого хватило за глаза на 2 дня и нескольких сотен участников. Для редких подключений нескольких человек достаточно 2cpu2ram.

**Comment by oserikov** [comment]
Спасибо!
